---
title: "SBCK Watershed Brigade Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
---


```{r}
# Load necessary packages
library(tidyverse) # For data wrangling
library(leaflet) # For mapping 
library(googlesheets4) # For loading data from Google Sheets
library(flexdashboard) # Tools for making the dashboard
library(DT)
```

```{r}
# Read in raw data from Google Sheets 
# Sheet is publically available to view, so force deauth
gs4_deauth()
watershed_brigade_data_raw <- read_sheet("1SVNe7XiDKMprvO3PnNbQBSRoYau1JbyqwHhx6Dz67jc",
                                         col_types = "c",
                                         skip = 1) 
# Process data
watershed_brigade_data_processed <- watershed_brigade_data_raw %>% 
  # Don't want these rows
  filter(!(Name %in% c("Totals","Points","Name"))) %>%
  filter(!str_detect(Name,"Total")) %>%
  # Require there to be a name
  filter(!is.na(Name)) %>%
  # This gets rid of header rows that have things like "January 2021"
  mutate(Date = lubridate::mdy(Date)) %>%
  # Add month name column
  mutate(Month = lubridate::month(Date,label=TRUE,abbr = FALSE),
         # Add year number column
         Year = lubridate::year(Date),
         # Add month number, for sorting
         month_number = lubridate::month(Date)) %>%
  # Don't want rows that don't have a date
  filter(!is.na(Date)) %>%
  # Convert weight to numeric pounds
  mutate(weight_pounds = as.numeric(`weight (lbs)`),
         group_total = as.numeric(`Group total`)) %>%
  # Add column for cleanup event ids
  mutate(cleanup_event_id = paste0(Date,"_",Location)) %>%
  # Add extra volunteers, in cases when group_total is >1
  # This will be used to count number of unique volunteers
  mutate(add_multiple_volunteers = ifelse(group_total>1,
                                          group_total-1,
                                          0))  %>%
  # Extract coordinates following this example: https://stackoverflow.com/questions/39009626/r-sets-of-coordinates-extract-from-string/39010020#39010020
  mutate(coordinates_2 = gsub('\\([^)]+\\)', '', Coordinates),
         coordinates_2 = gsub('(\\d+[.]\\d+)[.]\\d+', '\\1', Coordinates)) %>%
  separate(coordinates_2, c( 'lat','lon'), fill = 'right', sep = '[,/]', convert = TRUE) %>%
  mutate(lat = as.numeric(lat),
         lon =as.numeric(lon)) %>%
  # Make points numeric, so we can count them
  mutate(points = as.numeric(points))

##### Let's calculate some statistics for the dashboard

# How many unique volunteers were there?
# Count up distinct number of names
# Then add extra volunteers, in cases when the group size was >1
number_unique_volunters <-
  n_distinct(watershed_brigade_data_processed$Name) +
  sum(watershed_brigade_data_processed$add_multiple_volunteers,
      na.rm=TRUE)

# How many pounds of trash were cleaned up?
number_pounds_trash <- sum(watershed_brigade_data_processed$weight_pounds,
                           na.rm=TRUE) %>%
  # Round this
  round()

# How many unique cleanup events were there?
number_volunteer_events <- n_distinct(watershed_brigade_data_processed$cleanup_event_id)
```

Row
-----------------------------------------------------------------------

### Volunteers {.value-box}

```{r}
# Icon names are from here: https://fontawesome.com/icons/users?s=solid&f=classic
valueBox(value = prettyNum(number_unique_volunters, 
                           big.mark = ","),
         icon = "fa-users")
```

### Pounds of Trash {.value-box}

```{r}
# Icon names are from here: https://fontawesome.com/icons/users?s=solid&f=classic
valueBox(value = prettyNum(number_pounds_trash, 
                           big.mark = ","),
         icon = "fa-trash")
```

### Events {.value-box}

```{r}
# Icon names are from here: https://fontawesome.com/icons/users?s=solid&f=classic
valueBox(value = prettyNum(number_volunteer_events, 
                           big.mark = ","),
         icon = "fa-calendar-check")
```

Row
-----------------------------------------------------------------------

### Cumulative Cleanup Map

```{r}
leaflet(data = watershed_brigade_data_processed) %>%
  addTiles() %>%
  # setView(lng = -119.6982,
  #         lat = 34.4208,
  #         zoom = 9) %>%
  addMarkers(lng = ~lon,
             lat = ~lat,
             clusterOptions = markerClusterOptions(),
             popup = ~paste0("<strong>Month: </strong>",as.character(Month),"<br>",
                             "<strong>Name: </strong>",as.character(Name),"<br>",
                             "<strong>Date: </strong>",as.character(Date),"<br>",
                             "<strong>Group size: </strong>",as.character(group_total),"<br>",
                             "<strong>Place: </strong>",as.character(Location),"<br>",
                             "<strong>Weight (lbs): </strong>",as.character(weight_pounds),"<br>",
                             "<strong>Bag(s): </strong>",as.character(`Amount of trash (bags)`),"<br>",
                             "<strong>Time (hours): </strong>",as.character(Hours)))
```

### The Monthly Scoreboard: Participants and Points earned in the current Monthly Challenge

```{r}
# What is current year for challenge?
current_year <- max(watershed_brigade_data_processed$Year,na.rm=TRUE)

# What is current month?
current_month <- watershed_brigade_data_processed %>%
  filter(Year == current_year) %>%
  .$month_number %>%
  max(na.rm=TRUE)

# Summarize total points by name and month for monthly volunteer summary
monthly_volunteer_summary <- watershed_brigade_data_processed %>% 
  group_by(Name,
           Year,
           Month,
           month_number) %>%
  summarize(Points = sum(points,na.rm=TRUE)) %>%
  ungroup() %>%
  # Just look at latest year and month 
  filter(Year == current_year,
         month_number == current_month) %>%
  arrange(-Points) %>%
  dplyr::select(-month_number)

monthly_volunteer_summary %>%
  datatable(options = list(dom = 't',
                           pageLength = nrow(monthly_volunteer_summary)))
```

Row
-----------------------------------------------------------------------

### Watershed Brigade Monthly Cummulative Clean-up Chart

```{r}
# Using same approach as above, summarize monthly sites, volunteers, and pounds of trash
monthly_total_summary <- watershed_brigade_data_processed %>%
  group_by(Year,
           Month,
           month_number) %>%
  summarize(`Number of sites cleaned` = n_distinct(Location),
            `Number of volunteers` = n_distinct(Name) + sum(add_multiple_volunteers,na.rm=TRUE),
            `Total pounds of trash` = round(sum(weight_pounds, na.rm = TRUE))) %>%
  ungroup() %>%
  arrange(-Year,-month_number) %>%
  dplyr::select(-month_number)

monthly_total_summary %>%
  datatable(options = list(dom = 't',
                           pageLength = nrow(monthly_total_summary)))
```
Row {data-height=50}
-----------------------------------------------------------------------

### Last updated: `r lubridate::with_tz(Sys.time(),tzone = "America/Los_Angeles")` Santa Barbara time.
