on:
  push:
    paths:
      - docs/index.Rmd
      - .github/workflows/render-website.yaml
  schedule:
    # Runs "At 6am UTC on every day-of-week from Tuesday through Saturday", time in UTC
    # https://jasonet.co/posts/scheduled-actions/
    - cron: '0 6 * * 2-6'

env:
  RENV_PATHS_ROOT: ~/Library/Application Support/renv

name: Render my document

jobs:
  render:
    name: Render my document
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      - name: Render document
        run: Rscript -e 'rmarkdown::render("docs/index.Rmd", output_format = "all")'
      - name: Commit results
        run: |
          git add docs/index*
          git commit -m 'Re-build index' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
