on:
  push:
    paths:
      - docs/index.Rmd
  schedule:
    # Runs "At 11:05 on every day-of-week from Monday through Friday"
    - cron: '13 18 * * 1-5'

name: Render my document

jobs:
  render:
    name: Render my document
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Install tidyverse
        run: Rscript -e 'install.packages("tidyverse")'
      - name: Install flexdashboard
        run: Rscript -e 'install.packages("flexdashboard")'
      - name: Install leaflet
        run: Rscript -e 'install.packages("leaflet")'
      - name: Install googlesheets4
        run: Rscript -e 'install.packages("googlesheets4")'
      - name: Install DT
        run: Rscript -e 'install.packages("DT")'
      - name: Render my document to all types
        run: Rscript -e 'rmarkdown::render("docs/index.Rmd", output_format = "all")'
      - name: Commit results
        run: |
          git add docs/index*
          git commit -m 'Re-build index' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
